######################################################################
## modified by walter: You need to put the correct: IBAMR_SRC_DIR and IBAMR_BUILD_DIR
## for 2D code: 1) change PDIM=2 2) run make main2D -j 2
## for 3D code: 1) change PDIM=3 2) run make main3D -j 2 
##
## Here specify the location of the IBAMR source and the location
## where IBAMR has been built.
IBAMR_SRC_DIR =$(HOME)/SOFTWARES/LIBRARIESIBAMR/IBFE2015_quadrature/IBAMR
IBAMR_BUILD_DIR =$(HOME)/SOFTWARES/LIBRARIESIBAMR/IBFE2015_quadrature/ibamr-objs-opt
######################################################################
## Include variables specific to the particular IBAMR build.
include $(IBAMR_BUILD_DIR)/config/make.inc

######################################################################
## Build the IB tester application.

## DIMENSIONALITY
PDIM=2
PD=$(PDIM)D
## SOURCE FILES 
Source = main.C 


## OBJECT FILES
OBJS$(PD) = main.o 

## DIMENSIONALITY
LIBS += -lcurl
LIBS += -lnetcdf


#########################################################################
## Rules

default: check-opt main$(PD)


main$(PD): $(IBAMR_LIB_$(PD)) $(IBTK_LIB_$(PD)) $(OBJS$(PD))
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(OBJS$(PD)) \
	$(IBAMR_LIB_$(PD)) $(IBTK_LIB_$(PD)) $(LIBS) -DNDIM=$(PDIM) -o $@


check-opt:
	if test "$(OPT)" == "1" ; then				\
	  if test -f stamp-debug ; then $(MAKE) clean ; fi ;	\
	  touch stamp-opt ;					\
	else							\
	  if test -f stamp-opt ; then $(MAKE) clean ; fi ;	\
	  touch stamp-debug ;					\
	fi ;

clean:
	$(RM) stamp-{opt,debug}
	$(RM) *.o *.lo *.objs *.ii *.int.c
	$(RM) -r .libs
	$(RM) ../../*.o


depend:
	makedepend -s "# THE FOLLOWING IS AUTOMATICALLY GENERATED BY MAKEDEPEND" \
	-- -DNDIM=$(PDIM) $(CPPFLAGS) -- $(SOURCES_$(PD)_ZF)

######################################################################
# THE FOLLOWING IS AUTOMATICALLY GENERATED BY MAKEDEPEND
